version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

formatters:
  enable:
    - gofmt
    - golines
    - goimports

linters:
  enable:
    - govet
    - staticcheck
    - ineffassign
    - unused
  disable:
    - errcheck
